export const scannerSummary = {
  raw_markets: 42,
  normalized_markets: 39,
  passed_count: 7,
  rejected_count: 32,
  pass_rate: 0.1795,
  skip_reason_counts: {
    category_not_allowed: 11,
    spread_too_wide: 8,
    liquidity_too_low: 6,
    missing_orderbook: 4,
    already_open_position: 3,
  },
  skip_reason_examples: {
    category_not_allowed: [
      "KXNBAWEST-26MAY19-LAL",
      "KXMLB-26MAY19-NYYBOS",
    ],
    spread_too_wide: [
      "KXBTC-26MAY20-110000",
      "KXETH-26MAY20-4000",
    ],
    liquidity_too_low: [
      "KXFEDDECISION-26JUN18-HIKE",
      "KXOIL-26MAY24-72",
    ],
    missing_orderbook: ["KXWEATHERNYC-26MAY22-RAIN"],
    already_open_position: ["KXINFLATION-26JUN10-CPI"],
  },
  candidates_analyzed: 5,
  execute_paper: false,
  dry_run: true,
  decisions: [
    {
      ticker: "KXFEDDECISION-26JUN18-NOHIKE",
      action: "BUY_YES",
      executed: false,
      execution_skip_reason: "execute_paper_not_requested",
      threshold_passed: true,
      risk_approved: true,
      decision: {
        action: "BUY_YES",
        ticker: "KXFEDDECISION-26JUN18-NOHIKE",
        side: "yes",
        limit_price_cents: 63,
        contracts: 12,
        dollar_size: 75.6,
        thesis: "Consensus pricing has lagged updated rate guidance and recent macro data.",
        edge_cents: 4.8,
        confidence: 0.8,
        risk_summary: "approved (paper, 6 checks passed): within category and daily exposure limits",
        monitoring_plan: [
          "Watch spread, max 5c before re-evaluating",
          "Re-check thesis after new Fed speaker headlines",
        ],
      },
    },
    {
      ticker: "KXCPI-26JUN10-ABOVE3",
      action: "NO_TRADE",
      executed: false,
      execution_skip_reason: "no_trade",
      threshold_passed: false,
      risk_approved: false,
      decision: {
        action: "NO_TRADE",
        ticker: "KXCPI-26JUN10-ABOVE3",
        side: null,
        limit_price_cents: 0,
        contracts: 0,
        dollar_size: 0,
        thesis: "The model sees directionally interesting inflation risk, but not enough edge after fees and spread.",
        edge_cents: 1.1,
        confidence: 0.65,
        risk_summary: "edge_below_threshold; risk_rejected: insufficient adjusted edge",
        monitoring_plan: [],
      },
    },
    {
      ticker: "KXOIL-26MAY24-ABOVE72",
      action: "BUY_NO",
      executed: false,
      execution_skip_reason: "execute_paper_not_requested",
      threshold_passed: true,
      risk_approved: true,
      decision: {
        action: "BUY_NO",
        ticker: "KXOIL-26MAY24-ABOVE72",
        side: "no",
        limit_price_cents: 41,
        contracts: 9,
        dollar_size: 36.9,
        thesis: "Inventory surprise was already absorbed while liquidity remains supportive for a small paper position.",
        edge_cents: 3.2,
        confidence: 0.65,
        risk_summary: "approved (paper, 5 checks passed): small size within commodity exposure cap",
        monitoring_plan: ["Watch intraday crude breakouts", "Re-check if spread widens above 5c"],
      },
    },
    {
      ticker: "KXUNEMPLOY-26JUN05-ABOVE42",
      action: "NO_TRADE",
      executed: false,
      execution_skip_reason: "candidate_failed: research timeout",
      threshold_passed: false,
      risk_approved: false,
      decision: {
        action: "NO_TRADE",
        ticker: "KXUNEMPLOY-26JUN05-ABOVE42",
        side: null,
        limit_price_cents: 0,
        contracts: 0,
        dollar_size: 0,
        thesis: "No thesis available because candidate analysis did not finish.",
        edge_cents: 0,
        confidence: 0.3,
        risk_summary: "candidate_failed: research timeout",
        monitoring_plan: [],
      },
    },
    {
      ticker: "KXGDP-26JUL31-ABOVE25",
      action: "NO_TRADE",
      executed: false,
      execution_skip_reason: "risk_not_approved",
      threshold_passed: true,
      risk_approved: false,
      decision: {
        action: "NO_TRADE",
        ticker: "KXGDP-26JUL31-ABOVE25",
        side: null,
        limit_price_cents: 0,
        contracts: 0,
        dollar_size: 0,
        thesis: "Edge is positive but overlaps too closely with existing macro paper exposure.",
        edge_cents: 2.9,
        confidence: 0.8,
        risk_summary: "risk_rejected: correlated exposure limit reached",
        monitoring_plan: [],
      },
    },
  ],
  paper_trades_inserted: 0,
  errors: [
    {
      stage: "candidate",
      ticker: "KXUNEMPLOY-26JUN05-ABOVE42",
      err: "research timeout",
    },
  ],
};
